version: '3'

services:
  # Serviço que irá rodar o node
  node:
    # Imagem base do container
    image: node:16.14
    # Nome do container para facilitar execução
    container_name: teste_container_boaz
    # Caminho da Dockerfile
    build: ./ 
    # Restarta a imagem caso algo a faça parar
    restart: always
    # Diretório padrão de execução
    working_dir: /app
    # Lista de volumes (diretórios) mapeados de fora para dentro do container
    volumes:
      # Monta o diretório atual, com todos os dados do projeto, 
      # dentro do diretório /app
      - ./:/app
    # Lista de portas mapeadas de dentro para fora do container
    # na notação porta_de_fora:porta_de_dentro
    ports:
      # Expõe a porta padrão da aplicação: altere aqui caso use outra porta
      - 3007:3007